name: Deploy Laravel Authentication Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - laravel-subspace-authentication/**
      - .github/workflows/laravel-subspace-authentication-deploy.yml
      - docker-compose.yml
      - Dockerfile


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: laravel-production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          script: |
            cd ~/web-subspace
            git pull origin master
            docker-compose up -d --build laravel-subspace-authentication
            echo 'Laravel Auth Service Updated'