name: Deploy Laravel Authentication Microservice

on:
  push:
    branches:
      - master
    paths:
      - laravel-subspace-authentication/**
      - .github/workflows/laravel-subspace-authentication-deploy.yml
      - docker-compose.yml
      - Dockerfile


jobs:
  test:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.TEST_ADDRESS }}
          username: ${{ secrets.TEST_USERNAME }}
          key: ${{ secrets.TEST_PRIVATE_KEY }}
          passphrase: ${{ secrets.TEST_PASSPHRASE }}
          script: |
            cd ~
            echo 'Connected To Server'
  # deploy:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Run update command
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.HOST_ADDRESS }}
  #         username: ${{ secrets.HOST_USERNAME }}
  #         key: ${{ secrets.PRODUCTION_PRIVATE_SSH_KEY }}
  #         passphrase: ${{ secrets.HOST_PASSPHRASE }}
  #         port: 22
  #         script: |
  #           cd ~/web-subspace
  #           git pull origin master
  #           docker-compose up -d --build laravel-subspace-authentication
  #           echo 'Deployment to digital ocean finished'