name: Deploy Laravel Community Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - laravel-subspace-community/**
      - .github/workflows/laravel-subspace-community-deploy.yml
      - docker-compose.yml
      - Dockerfile


jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          key: ${{ secrets.HOST_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~/web-subspace
            git pull origin master
            docker-compose up -d --build laravel-subspace-community
            echo 'Laravel Community Service Updated'