name: Deploy Laravel Authentication Microservice

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - laravel-subspace-authentication/**
      - .github/workflows/laravel-subspace-authentication-deploy.yml
      - docker-compose.yml
      - Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: mysql
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_USERNAME: ${{ secrets.DB_USERNAME }}
      DB_PORT: 25060
      DB_DATABASE: subspace-auth
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo
          coverage: xdebug

      - name: Install composer dependencies
        run: composer install --working-dir=laravel-subspace-authentication

      - name: Create app key
        run: echo "APP_KEY=$(php laravel-subspace-authentication/artisan key:generate --show)" >> $GITHUB_ENV

      - name: Run authentication microservice
        run: nohup php laravel-subspace-authentication/artisan serve &

      - name: Run tests with PHP Unit
        run: cd laravel-subspace-authentication && vendor/bin/phpunit tests

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment: laravel-production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_ADDRESS }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: 22
          script: |
            cd ~/web-subspace
            git pull origin master
            docker-compose up -d --build laravel-subspace-authentication
            echo 'Laravel Auth Service Updated'
